<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>33ErgebnisTest</name>
   <tag></tag>
   <elementGuidId>e8afdc00-3bbd-46e6-b4a8-05a9340c220d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[2]/div[3]/main/div/div[2]/div[2]/div[2]/div/div[33]/a/span</value>
   </webElementProperties>
</WebElementEntity>
