<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Akkordeon07</name>
   <tag></tag>
   <elementGuidId>1baaba6c-9eb1-4bc3-a21f-0e9de7d64e9d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>((//div[@class=&quot;stickynav__list&quot;])[1]//a[@class=&quot;stickynav__item&quot;])[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>((//div[@class=&quot;stickynav__list&quot;])[1]//a[@class=&quot;stickynav__item&quot;])[4]</value>
   </webElementProperties>
</WebElementEntity>
