<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Akkordeon04</name>
   <tag></tag>
   <elementGuidId>c2adaece-d14d-441e-944a-b6a564650ea2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>((//ul[@class=&quot;stickynav__list&quot;])[1]//li[@class=&quot;stickynav__item&quot;])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>((//ul[@class=&quot;stickynav__list&quot;])[1]//li[@class=&quot;stickynav__item&quot;])[1]</value>
   </webElementProperties>
</WebElementEntity>
