<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Akkordeon06</name>
   <tag></tag>
   <elementGuidId>f8973791-e155-4b51-94c3-560b4d5b86ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//li[@class=&quot;stickynav__item&quot;])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//li[@class=&quot;stickynav__item&quot;])[3]</value>
   </webElementProperties>
</WebElementEntity>
