<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Akkordeon05</name>
   <tag></tag>
   <elementGuidId>2be1f1a0-f953-4446-9992-10e7ff831793</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//li[@class=&quot;stickynav__item&quot;])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//li[@class=&quot;stickynav__item&quot;])[2]</value>
   </webElementProperties>
</WebElementEntity>
