<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>b72351d9-3c58-4c03-9b9c-5148e70392f7</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.vr.de/privatkunden/_jcr_content/kampagnenbereich/karussell/parsys/kampagnecomponent_343591381/kampagne/bild.img.png/1522842993250/kampagne-mitgliedschaft-bvr-1600x550_1.jpg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Leistungen der Volksbanken Raiffeisenbanken</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Leistungen der Volksbanken Raiffeisenbanken</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>border</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wcbody&quot;)/div[@class=&quot;campaign-area&quot;]/div[@class=&quot;module module-carousel   l-fade has-swipe&quot;]/div[@class=&quot;carousel-wrapper&quot;]/div[@class=&quot;carousel-item-wrap count_0 carousel__item--visible carousel__item--primary&quot;]/div[@class=&quot;section-teaser   klick-track_PK-Header1 js-ready&quot;]/a[@class=&quot;-cta&quot;]/div[@class=&quot;c-image&quot;]/img[1]</value>
   </webElementProperties>
</WebElementEntity>
