<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_dropdown-icons</name>
   <tag></tag>
   <elementGuidId>6314cc4b-1ff3-43e5-900e-6ab2bf6babb6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//svg[count(. | id(&quot;aps-dropdown-button&quot;)/svg[@class=&quot;dropdown-icons&quot;]) = count(id(&quot;aps-dropdown-button&quot;)/svg[@class=&quot;dropdown-icons&quot;])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@class = 'combo-field']/span[contains(@class, 'ui-selectmenu-button')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-icons</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>focusable</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;aps-dropdown-button&quot;)/svg[@class=&quot;dropdown-icons&quot;]</value>
   </webElementProperties>
</WebElementEntity>
