<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>53ErgebnisTest</name>
   <tag></tag>
   <elementGuidId>4bacd0fa-2c7e-4b35-ac1e-a08ef7d1152c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//div[@class=&quot;accordeon has-pager&quot;]//span[@class=&quot;loc-name&quot;])[53]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[2]/div[3]/main/div/div[2]/div[2]/div[2]/div/div[53]/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[2]/div[3]/main/div/div[2]/div[2]/div[2]/div/div[53]/a/span</value>
   </webElementProperties>
</WebElementEntity>
