<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_iOS</name>
   <tag></tag>
   <elementGuidId>824eaf09-0b9e-4eb6-b493-7428113b1c30</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>smslayer__service__ios</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>iOS</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/div[@class=&quot;wrapper ym-cbox-right&quot;]/div[@class=&quot;layout-wrapper&quot;]/div[@class=&quot;layout-wrapper-inner&quot;]/div[@class=&quot;smslayer&quot;]/div[@class=&quot;smslayer__inner ym-clearfix&quot;]/div[@class=&quot;smslayer__formular formular ym-clearfix&quot;]/form[@class=&quot;smslayer__inner&quot;]/fieldset[1]/div[@class=&quot;row select-row l-col error&quot;]/ul[@class=&quot;group ym-clearfix&quot;]/li[1]/label[1]</value>
   </webElementProperties>
</WebElementEntity>
