<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_aps-map__custom-marker</name>
   <tag></tag>
   <elementGuidId>5a23ce6a-5213-4541-bedd-050a6b74ff39</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>aps-map__custom-marker</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/div[@class=&quot;wrapper ym-cbox-right&quot;]/div[@class=&quot;module-aps ym-clearfix&quot;]/div[@class=&quot;aps-map&quot;]/div[@class=&quot;aps-map__canvas&quot;]/div[1]/div[@class=&quot;gm-style&quot;]/div[1]/div[4]/div[1]/div[@class=&quot;aps-map__custom-marker&quot;]</value>
   </webElementProperties>
</WebElementEntity>
