<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>2teSeite - Copy</name>
   <tag></tag>
   <elementGuidId>468c1a33-d12b-4057-a1b1-da33e0d9d05e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[2]/div[3]/main/div/div[2]/div[2]/div[2]/div/div[20]/ul/li[4]/a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//li[@class=&quot;page&quot;])[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[2]/div[3]/main/div/div[2]/div[2]/div[2]/div/div[20]/ul/li[4]/a</value>
   </webElementProperties>
</WebElementEntity>
