<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_dropdown-icons</name>
   <tag></tag>
   <elementGuidId>3ca1d63b-5e9f-4fef-85b7-5cd2a33cffed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@class = 'combo-field']/span[@class = 'ui-selectmenu-button ui-selectmenu-button-closed ui-corner-all ui-button ui-widget']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;aps-dropdown-widget-1-button&quot;)/svg[@class=&quot;dropdown-icons&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-icons</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>focusable</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;aps-dropdown-widget-1-button&quot;)/svg[@class=&quot;dropdown-icons&quot;]</value>
   </webElementProperties>
</WebElementEntity>
