<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Zurck</name>
   <tag></tag>
   <elementGuidId>de834042-5b45-446e-84c6-71481f16c30c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[@href = '#' and @title = 'Zurück' and (text() = 'Zurück' or . = 'Zurück')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@class=&quot;megafooter-slider l-slide has-swipe&quot;]/div[@class=&quot;carousel-nav&quot;]/a[@class=&quot;prev&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>prev</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Zurück</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Zurück</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wcbody&quot;)/div[@class=&quot;megafooter&quot;]/div[@class=&quot;megafooter-inner-full&quot;]/div[@class=&quot;megafooter-slider l-slide has-swipe&quot;]/div[@class=&quot;carousel-nav&quot;]/a[@class=&quot;prev&quot;]</value>
   </webElementProperties>
</WebElementEntity>
