<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Akkordeon09</name>
   <tag></tag>
   <elementGuidId>66baed1e-4800-4efb-8933-8a2a4b9f9a20</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>((//div[@class=&quot;acc-wrapper&quot;])[9]//a[@class=&quot;acc-header&quot;])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>((//div[@class=&quot;acc-wrapper&quot;])[9]//a[@class=&quot;acc-header&quot;])[1]</value>
   </webElementProperties>
</WebElementEntity>
