<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Akkordeon01</name>
   <tag></tag>
   <elementGuidId>f09e821d-0f8c-4d95-b595-4684964ddad3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>((//div[@class=&quot;acc-wrapper&quot;])[1]//a[@class=&quot;acc-header&quot;])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>((//div[@class=&quot;acc-wrapper&quot;])[1]//a[@class=&quot;acc-header&quot;])[1]</value>
   </webElementProperties>
</WebElementEntity>
