<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Akkordeon03</name>
   <tag></tag>
   <elementGuidId>f391ed23-f87d-4581-bb8c-2b174e7e63c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>((//div[@class=&quot;acc-wrapper&quot;])[3]//a[@class=&quot;acc-header&quot;])[1]</value>
   </webElementProperties>
</WebElementEntity>
