<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_1</name>
   <tag></tag>
   <elementGuidId>ab3180a4-90e5-41e6-a787-aeec1c6dc6a3</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wcbody&quot;)/div[@class=&quot;campaign-area&quot;]/div[@class=&quot;module module-carousel   l-fade has-swipe&quot;]/div[@class=&quot;carousel-nav&quot;]/ul[@class=&quot;pagination&quot;]/li[1]</value>
   </webElementProperties>
</WebElementEntity>
