<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_module-lebenseinstieg--tea</name>
   <tag></tag>
   <elementGuidId>ea857ab2-23e2-4470-a590-1997535b3ed2</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>module-lebenseinstieg--teaser-image</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/content/dam/f0906-6/individualisierung/internetneu_1/layout/img/trans.gif</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Zahlungsverkehr für Unternehmen</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/div[@class=&quot;wrapper ym-cbox-right&quot;]/div[@class=&quot;layout-wrapper padding-top einstieg-firmenkunden&quot;]/div[@class=&quot;layout-wrapper-inner&quot;]/div[@class=&quot;module module-lebenseinstieg&quot;]/ul[@class=&quot;path-8&quot;]/li[@class=&quot;lebenseinstieg einstieg-4&quot;]/a[1]/div[@class=&quot;module-lebenseinstieg--teaser-container&quot;]/picture[1]/img[@class=&quot;module-lebenseinstieg--teaser-image&quot;]</value>
   </webElementProperties>
</WebElementEntity>
