<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Akkordeon02</name>
   <tag></tag>
   <elementGuidId>ff7ce5b4-2ebf-462a-ad76-b05ac8ffa17b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>((//div[@class=&quot;acc-wrapper&quot;])[2]//a[@class=&quot;acc-header&quot;])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>((//div[@class=&quot;acc-wrapper&quot;])[2]//a[@class=&quot;acc-header&quot;])[1]</value>
   </webElementProperties>
</WebElementEntity>
