<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Akkordeon05</name>
   <tag></tag>
   <elementGuidId>569a07b1-69f0-4de8-942d-21692f5d9550</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>((//div[@class=&quot;acc-wrapper&quot;])[5]//a[@class=&quot;acc-header&quot;])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>((//div[@class=&quot;acc-wrapper&quot;])[5]//a[@class=&quot;acc-header&quot;])[1]</value>
   </webElementProperties>
</WebElementEntity>
