<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Akkordeon35</name>
   <tag></tag>
   <elementGuidId>146747b0-3604-435f-b752-8bd5d5ce6529</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[2]/div[3]/main/div/div[9]/div[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[2]/div[3]/main/div/div[9]/div[3]/a</value>
   </webElementProperties>
</WebElementEntity>
